### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by sangwoo108** [brave/playlist-component#2]
Update LICENSE file and each file's license.

**Comment by sangwoo108** [comment]
Hi, @bsclifton . This repo contains scripts that will be updated via package manager. I wonder what license should be applied to files in this repo. Is MPL basic licens for us?

**Comment by bsclifton** [comment]
@sangwoo108 I believe MPL will be perfect. cc: @fmarier just to triple check 😄

**Comment by bbondy** [comment]
Yes MPL2 pls

**Comment by fmarier** [comment]
@sangwoo108 Also see #3 which I just filed.
